### ISSUE TITLE
Request : Sum Co-Planar Areas

### ISSUE THREAD

**Issue by ArieLeo** [fedackb/yavne#6]
Now this add on are really great it's almost perfect just like Modo Normal Toolkit.
Only one function that i think it's missing which is, Sum Co-Planar Areas
![image](https://user-images.githubusercontent.com/6450517/31831686-de8398b0-b5f6-11e7-8fee-c4a2b60fd53c.png)
![image](https://user-images.githubusercontent.com/6450517/31831721-01b784c2-b5f7-11e7-8e6f-5d43720d82ae.png)
now you can see that the Co-Planar angle threshold really help defining the vertex normal on area where the vertices flow are uneven/or non quad
![image](https://user-images.githubusercontent.com/6450517/31831811-5d6fa100-b5f7-11e7-8066-2b5f7fac35de.png)

**Comment by fedackb** [comment]
I'm closing this issue since the requested feature was implemented in version 1.9.0.
