### ISSUE TITLE
Plans to port yavne to 2.8?

### ISSUE THREAD

**Issue by fracteed** [fedackb/yavne#8]
Was wondering if there are plans to port yavne to Blender 2.8 when the beta is stable enough? I have come to rely heavily on yavne since I started using it, and it completely changed my workflow for modelling game assets with Blender, so many thanks for developing it!

**Comment by Adder1812** [comment]
Exactly like my workflow, so i hope so.. This is the best plugin for blender ever. I would pay for it ;D

**Comment by kurzemnieks** [comment]
yes, please - very useful addon. It would be nice to have it in 2.8!

**Comment by fredrickaven** [comment]
*nudge nudge*. Not having this for 2.8 is the only thing stopping me from swapping over.

**Comment by xissburg** [comment]
In Blender 2.80 in Edit Mode you can press option/alt+N or go to Mesh > Normals to access tools similar to yavne. Here are the [docs](https://docs.blender.org/manual/en/dev/modeling/meshes/editing/normals.html#custom-split-normals). I just found this so I'm not sure it can do everything yavne does but it does what I need such as creating rounded edges.

**Comment by Adder1812** [comment]
@xissburg AWESOME!!

**Comment by fracteed** [comment]
@xissburg have you managed to get sharp edges working in conjunction with the weighted normal modifier in 2.8? I have been playing around with it for months, but could never manage to get that to work. There is a "keep sharp" option but it sharpens all edges, not edges marked sharp.

The only way I have been able to do it, is to put an edge split modifier before the weighted normals modifier. This does work, but I would rather just modify normals the way yavne does it. hard to know if this is a bug or not?

**Comment by xissburg** [comment]
@fracteed I have never used the Weighted Normal modifier but you can make sharp edges by selecting them and then Mesh > Normals > Split

**Comment by fracteed** [comment]
@xissburg I had assumed that you need the weighted normal modifier to use face weighted normal workflow in 2.8. Just had a play with doing it manually and the workflow seems convoluted.

Would be very interested to know your workflow for this! Are you using the set from faces command after you have used the set face strength command? It only seems to update the normals if I do the set face command after I use the set from face command.

At least I am getting hard edges easily now, but the workflow is much nicer when using the modifier. Since the workflow doesn't seem to be documented anywhere ,maybe I am missing something obvious here :)

**Comment by xissburg** [comment]
@fracteed yes I use _Set From Faces_ basically. _Set Face Strength_ does nothing for me though. Not sure why.

**Comment by fracteed** [comment]
@xissburg for the life of me, I cannot get the non-modifer workflow to work properly. On the plus side, I did get the sharp edges and modifier workflow working. Ironically enough I got the info from a blender artists post of my own from 6 months ago...doh! I had forgotten that I had already worked it out, as I hadn't touched 2.8 in a while. It is very unintuitive, but does work...

https://blenderartists.org/t/rohans-bevel-gsoc-work-is-now-officially-in-2-8/1121995/22

Requoting myself for anyone interested. It does still make me crave yavne in 2.8 though!

Since the workflow is not at all intuitive, for anyone else wondering how to do this, these steps work well for me. (to get sharp edges working with the weighted normals modifier)

-    select Object>shade smooth for your mesh
-    turn on Auto smooth in the object data properties and change the angle to 180 degrees (this may need to be lowered later but is a good starting point)
-    add the weighted normal modifier
-    turn on the keep sharp and face influence options in the modifier
-    change the modifier weight to 100 (I seemed to get better normals on flat faces by doing this, but this is most likely to depend on your mesh).
- now any edges that you have marked sharp will act accordingly!

**Comment by fedackb** [comment]
Y.A.V.N.E. now supports Blender 2.8.

**Comment by xissburg** [comment]
@fracteed wow that's an extensive discussion on the topic. I don't understand why they basically reinvented the wheel there instead of maybe incorporating yavne in blender 2.80 since it already is a great wheel and I think time would have been better spent polishing this nice wheel we already have right here.

Thanks for that workflow idea, I think it's faster than doing it manually in yavne in most cases.

**Comment by fracteed** [comment]
@xissburg as far as I know, the GSOC dev that created the new normal tools did base a lot of the workflow on yavne. It is however a bit more convoluted. I swear there is something buggy going on with the modifier and having to go through the list of steps above(which don't even make logical sense). One added gotcha that I recently found to this workflow, is that if you bool something out of your mesh, you either have to set the bool cutter to also have smooth shading before you bool. Or after applying the bool, set the mesh to flat shading and then back to smooth shading. 

Btw, you only have to do these steps if you want to mix in sharp edges with face weighted normals. Otherwise it is just a matter of adding the modifer, turning on autosmooth (at the default 30deg) and just tagging faces that don't automatically weight themselves correctly.

We now have the best of both worlds with the native tools (bevel modifier with harden normals option is particularly great!) and the new 2.8 yavne...many thanks to @fedackb for updating this!
